name: MediaTracker
version: "0.2.13"
slug: mediatracker
description: >-
  Track movies, TV shows, video games, books and audiobooks.
  Includes Home Assistant calendar integration via iCal feed.
url: https://github.com/muster021/MediaTracker
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ports:
  7481/tcp: 7481
ports_description:
  7481/tcp: MediaTracker Web UI & API
webui: "http://[HOST]:[PORT:7481]"
panel_icon: mdi:television-play
panel_title: MediaTracker
map:
  - type: data
    read_only: false
options:
  tmdb_lang: "en"
  server_lang: "en"
  audible_lang: "us"
  igdb_client_id: ""
  igdb_client_secret: ""
  log_level: "info"
schema:
  tmdb_lang: "str"
  server_lang: "str"
  audible_lang: "list(au|ca|de|es|fr|in|it|jp|uk|us)"
  igdb_client_id: "str?"
  igdb_client_secret: "password?"
  log_level: "list(debug|info|warn|error)"
